# Dockerfile for API Gateway
FROM golang:1.23-alpine AS builder

WORKDIR /app

WORKDIR /app
COPY ./go.mod ./go.sum .

WORKDIR /app/api-gateway
RUN go mod download

COPY api-gateway/ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/gateway ./cmd

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/gateway .

EXPOSE 8080

CMD ["./gateway"]
